# Generated by Django 6.0.6 on 2026-06-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_post_options_and_more'),
        ('userProfile', '0012_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='activity_po_created_81775e_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created'], name='activity_po_created_7586d1_idx'),
        ),
    ]
