# Generated by Django 6.0.6 on 2026-06-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_comment_user'),
        ('userProfile', '0012_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='activity_co_created_5563f4_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='activity_co_created_fe87b4_idx'),
        ),
    ]
