# Generated by Django 6.0.6 on 2026-06-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
