# Generated by Django 6.0.6 on 2026-06-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
